env:
  browser: false
  es2022: true

extends: 
- "eslint-config-standard-with-typescript"
- "eslint:recommended"
- "plugin:@typescript-eslint/eslint-recommended"
- "plugin:@typescript-eslint/recommended"

parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "tsconfig.json"
rules: {}
plugins:
- "jest"
- "@typescript-eslint"
ignorePatterns:
- "node_modules/"
- "dist/"
- "coverage/"
