name: "github-stats-card"
description: "Generate a minimal but inclusive github stats badge"
author: Bart6114
branding:
  icon: 'award'
  color: 'green'
inputs:
  username:
    description: "username to get stats for"
    required: true
    default: "bart6114"
  header:
    description: "header to use for badge"
    default: "👋 hi i'm"
  about:
    description: "about me description to use for badge (use \n for newlines)"
    default: "Loves goblins, despises gnomes.\nEnjoys candlelit custard pudding."
  theme: 
    description: "theme to use for badge"
    default: "dark"
  gh_token_stats:
    description: "github token to use to fetch user stats"
    required: true
  gh_token_commits:
    description: "github token to use to commit badge to repo, will default to stats token if not provided"
  badge_path:
    description: "path to save badge to (defaults to assets/badge.svg)"
    default: "assets/badge.svg"
  commit_message:
    description: "commit message to use when pushing badge to repo"
    default: "Update badge"
  commit: 
    description: "whether to commit badge to repo (defaults to true)"
    default: 'true'
  exclude_repos:
    description: "comma separated list of repos to exclude from stats, will do regex based matching (e.g. 'datarootsio' will match all repos in dataroots, 'datarootsio/databooks' will only match a single repo)"
    default: ""
  exclude_repos_override:
    description: "comma separated list of repos to override from exclusion list (e.g. 'datarootsio' in exclude_repos and 'datarootsio/databooks' in exclude_repos_override will ONLY include databooks in stats)"
    default: ""


outputs:
  badge_path: # id of output
    description: "Location of generated badge."
runs:
  using: "node16"
  main: "dist/index.js"
