name: ci

on: push

jobs:
  base-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm test
      - name: Rebuild the dist/ directory
        run: npm run prepare
      - uses: actions/upload-artifact@v3
        with:
          name: dist-artifact
          path: dist/

  badges:
    needs: base-ci
    runs-on: ubuntu-latest
    env: 
      GITHUB_TOKEN_STATS: ${{ secrets.GH_TOKEN }}
    strategy:
      matrix:
        theme:
        - dark
        - cool-lake
        - neko-sleeps
        - jimmy-goes-fishing
        - pad-and-paper
        - retro-print
        - terminal-green
        - tropical-sunset
        - hypnotoad
        - a-colibri-hums-while-the-dog-farts
        - grainy-dreams
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dist-artifact
          path: dist/
      - uses: ./
        name: github-stats-card
        with:
          username: murilo-cunha
          gh_token_stats: ${{ env.GITHUB_TOKEN_STATS }}
          gh_token_commits: ${{ secrets.GITHUB_TOKEN }}
          badge_path: assets/badge-${{ matrix.theme }}.svg
          commit: "false"
          theme: ${{ matrix.theme }}
          about: "Rust evangelist by day, dog whisperer by night,\nliving life between compile and fetch."

      - uses: actions/upload-artifact@v3
        with:
          name: badges-artifact
          path: assets/badge-${{ matrix.theme }}.svg

  commit-to-repo:
    needs: badges
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dist-artifact
          path: dist/
      - uses: actions/download-artifact@v3
        with:
          name: badges-artifact
          path: assets/
      - name: commit new files to repo
        uses: stefanzweifel/git-auto-commit-action@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0 
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          INITIAL_VERSION: 1.0.0
          DEFAULT_BUMP: patch
      - name: extract major version
        id: extract-major
        run: |
          major_version=$(echo "${{ steps.tag.outputs.new_tag }}" | cut -d '.' -f 1)
          echo "version=${major_version}" >> $GITHUB_OUTPUT
      - name: diplay major version
        run: |
          echo "The major version is: ${{ steps.extract-major.outputs.version }}"
      - name: automatic-draft-release
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          draft: false
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: "${{ steps.tag.outputs.tag }}"
          automatic_release_tag: ${{ steps.tag.outputs.new_tag }}
          prerelease: false
      - name: tag major if on main
        if: github.ref == 'refs/heads/main'
        run: |
          git tag -f "${{ steps.extract-major.outputs.version }}"
          git push -f origin "${{ steps.extract-major.outputs.version }}"